# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FdjZebjyxjjRQLPuzEaJ0S_dWiH0lN3r
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

# converting to one hot
data_one_hot = data.apply(lambda x: x.astype('category').cat.codes)
data_one_hot = pd.concat([data_one_hot, 1 - data_one_hot], axis=1)
data_one_hot.columns = ['human', 'robot']

data_one_hot.head()